# Form implementation generated from reading ui file 'qodex/ui/edit_document.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

class Ui_EditDocument(object):
    def setupUi(self, EditDocument):
        EditDocument.setObjectName("EditDocument")
        EditDocument.resize(400, 300)
        self.formLayout = QFormLayout(EditDocument)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QLabel(EditDocument)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label_2)
        self.path = QLabel(EditDocument)
        self.path.setText("")
        self.path.setObjectName("path")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.path)
        self.label = QLabel(EditDocument)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.label)
        self.title = QLineEdit(EditDocument)
        self.title.setObjectName("title")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.title)
        self.label_3 = QLabel(EditDocument)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_3)
        self.authors = QListView(EditDocument)
        self.authors.setObjectName("authors")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.authors)
        self.save_button = QPushButton(EditDocument)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.FieldRole, self.save_button)

        self.retranslateUi(EditDocument)
        QMetaObject.connectSlotsByName(EditDocument)

    def retranslateUi(self, EditDocument):
        _translate = QCoreApplication.translate
        EditDocument.setWindowTitle(_translate("EditDocument", "Form"))
        self.label_2.setText(_translate("EditDocument", "Path"))
        self.label.setText(_translate("EditDocument", "Title"))
        self.label_3.setText(_translate("EditDocument", "Authors"))
        self.save_button.setText(_translate("EditDocument", "Save"))
